server:
  port: 8081
spring:
  application:
    name: ronghua-crm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///crm?serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  type-aliases-package: org.chenzhiqiang.domain,org.chenzhiqiang.authority.domain,
                        org.chenzhiqiang.OperateMenu.domain,org.chenzhiqiang.sys.domain
#  配置扫描权限注解的包位置
authority:
  package: org.chenzhiqiang.controller,org.chenzhiqiang.authority.controller,org.chenzhiqiang.OperateMenu.controller
